services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - baza-danych    
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

  baza-danych:
    build:
      context: ./baza-danych
    container_name: baza-danych
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"  
